### ISSUE TITLE
If desire state contains no ip address entry, it will be copy from current address.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#109]
If I just remove the entire `address` section from ipv4 or ipv6, it will be added back before
apply.

**Comment by cathay4t** [comment]
```
Applying the following state:
interfaces:
- name: ens3
  type: ethernet
  state: up
  ipv4:
    address:
    - ip: 192.168.122.10
      prefix-length: 24
    enabled: true
  ipv6:
    enabled: false
  mtu: 1500
- name: lo
  type: unknown
  state: down
  ipv4:
    enabled: false
  ipv6:
    enabled: false
  mtu: 65536
2018-10-23 22:57:29,974 root         DEBUG    Connection update succeeded: dev=ens3
2018-10-23 22:57:29,995 root         DEBUG    Connection activation succeeded: dev=ens3, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
2018-10-23 22:57:29,995 root         DEBUG    NM action queue exhausted, quiting mainloop
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fge/Source/nmstate/nmstatectl/nmstatectl.py", line 49, in main
    return args.func(args)
  File "/home/fge/Source/nmstate/nmstatectl/nmstatectl.py", line 115, in edit
    netapplier.apply(new_state, verify_change=args.verify)
  File "/home/fge/Source/nmstate/libnmstate/netapplier.py", line 43, in apply
    _apply_ifaces_state(desired_state['interfaces'], verify_change)
  File "/home/fge/Source/nmstate/libnmstate/netapplier.py", line 65, in _apply_ifaces_state
    assert_ifaces_state(ifaces_desired_state, ifaces_current_state)
  File "/home/fge/Source/nmstate/libnmstate/netapplier.py", line 321, in assert_ifaces_state
    'desired: {}\ncurrent: {}'.format(iface_dstate, iface_cstate))
libnmstate.netapplier.DesiredStateIsNotCurrentError: desired: {'name': 'ens3', 'mtu': 1500, 'state': 'up', 'ipv4': {'enabled': True, 'address': [{'ip': '192.168.122.10', 'prefix-length': 24}]}, 'ipv6': {'enabled': False, 'address': [{'ip': 'fe80::5054:ff:fef8:d2a8', 'prefix-length': 64}]}, 'type': 'ethernet'}
current: {'state': 'up', 'name': 'ens3', 'ipv6': {'enabled': True, 'address': [{'ip': 'fe80::5054:ff:fef8:d2a8', 'prefix-length': 64}]}, 'mtu': 1500, 'type': 'ethernet', 'ipv4': {'enabled': True, 'address': [{'ip': '192.168.122.10', 'prefix-length': 24}]}}
```

**Comment by tyll** [comment]
The nmstate way to remove IP addresses is to specify an empty address section, does this work?

**Comment by tyll** [comment]
Please see #149

**Comment by cathay4t** [comment]
Yes. It works. Closing
