### ISSUE TITLE
 ERROR's with: libnmstate.error.NmstateLibnmError: Add profile: virbr0-nic failed with error: nm-connection-error-quark: connection.type: connection type 'unknown' is not valid (7)

### ISSUE THREAD

**Issue by hjensas** [nmstate/nmstate#1190]
## Describe the bug
Trying to create an OVS bridge and 4 OVS ports using nmstatectl set ovs-brides-state.yaml fail's on with an error related to a virbr0-nic interface that is not in the state yaml file.

## Nmstate version
nmstate-0.3.2-3.fc32.noarch

## NetworkManager version
NetworkManager-1.22.14-1.fc32.x86_64

## Platform
Fedora release 32 (Thirty Two)

## How reproducible
100%

## Steps to Reproduce
```
interfaces:
  - name: br-leafs
    type: ovs-bridge
    state: up
    bridge:
      options:
        stp: true
    port:
      - name: pxeleaf0
      - name: pxeleaf1
      - name: pxeleaf2
      - name: pxeleaf3

  - name: pxeleaf0
    type: ovs-interface
    state: up
    vlan: 600
    ipv4:
      enabled: true
      address:
        - ip: 172.20.0.62
          prefix-length: 26
      dhcp: false
    ipv6:
      enabled: true
      address:
        - ip: fd12:3456:789a:0::fffe
          prefix-length: 64
      autoconf: false
      dhcp: false
  - name: pxeleaf1
    type: ovs-interface
    state: up
    vlan: 601
    ipv4:
      enabled: true
      address:
        - ip: 172.20.0.126
          prefix-length: 26
      dhcp: false
    ipv6:
      enabled: true
      address:
        - ip: fd12:3456:789a:1::fffe
          prefix-length: 64
      autoconf: false
      dhcp: false
  - name: pxeleaf2
    type: ovs-interface
    state: up
    vlan: 602
    ipv4:
      enabled: true
      address:
        - ip: 172.20.0.190
          prefix-length: 26
      dhcp: false
    ipv6:
      enabled: true
      address:
        - ip: fd12:3456:789a:2::fffe
          prefix-length: 64
      autoconf: false
      dhcp: false
  - name: pxeleaf3
    type: ovs-interface
    state: up
    vlan: 603
    ipv4:
      enabled: true
      address:
        - ip: 172.20.0.254
          prefix-length: 26
      dhcp: false
    ipv6:
      enabled: true
      address:
        - ip: fd12:3456:789a:3::fffe
          prefix-length: 64
      autoconf: false
      dhcp: false

```

## Nmstate output
- Expected output:

- Current output:

```
2020-07-07 09:10:37,359 root         DEBUG    Async action: Create checkpoint started
2020-07-07 09:10:37,361 root         DEBUG    Checkpoint None created for all devices
2020-07-07 09:10:37,361 root         DEBUG    Async action: Create checkpoint finished
2020-07-07 09:10:37,362 root         DEBUG    Async action: Add profile: virbr0-nic started
2020-07-07 09:10:37,363 root         DEBUG    Async action: Add profile: br-leafs started
2020-07-07 09:10:37,363 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/1 rollback executed
2020-07-07 09:10:37,363 root         DEBUG    Async action: Rollback to checkpoint /org/freedesktop/NetworkManager/Checkpoint/1 started
2020-07-07 09:10:37,364 root         ERROR    Rollback failed with error Add profile: br-leafs failed with error: g-io-error-quark: Operation was cancelled (19)
Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==0.3.2', 'console_scripts', 'nmstatectl')()
  File "/usr/lib/python3.8/site-packages/nmstatectl/nmstatectl.py", line 67, in main
    return args.func(args)
  File "/usr/lib/python3.8/site-packages/nmstatectl/nmstatectl.py", line 251, in apply
    return apply_state(
  File "/usr/lib/python3.8/site-packages/nmstatectl/nmstatectl.py", line 282, in apply_state
    checkpoint = libnmstate.apply(
  File "/usr/lib/python3.8/site-packages/libnmstate/netapplier.py", line 71, in apply
    _apply_ifaces_state(plugins, net_state, verify_change, save_to_disk)
  File "/usr/lib/python3.8/site-packages/libnmstate/netapplier.py", line 104, in _apply_ifaces_state
    plugin.apply_changes(net_state, save_to_disk)
  File "/usr/lib/python3.8/site-packages/libnmstate/nm/plugin.py", line 177, in apply_changes
    nm_applier.apply_changes(self.context, net_state, save_to_disk)
  File "/usr/lib/python3.8/site-packages/libnmstate/nm/applier.py", line 129, in apply_changes
    context.wait_all_finish()
  File "/usr/lib/python3.8/site-packages/libnmstate/nm/context.py", line 216, in wait_all_finish
    raise tmp_error
libnmstate.error.NmstateLibnmError: Add profile: virbr0-nic failed with error: nm-connection-error-quark: connection.type: connection type 'unknown' is not valid (7)
```
### Additional context

nmstatectl show info related to ``virbr0`` and ``virbr0-nic``, the bridge and interface is the default created when installing libvirt.

```
- name: virbr0
  type: linux-bridge
  state: up
  bridge:
    options:
      group-forward-mask: 0
      mac-ageing-time: 300
      multicast-snooping: true
      stp:
        enabled: true
        forward-delay: 2
        hello-time: 2
        max-age: 20
        priority: 32768
    port:
    - name: virbr0-nic
      stp-hairpin-mode: false
      stp-path-cost: 100
      stp-priority: 32
  ipv4:
    address:
    - ip: 192.168.122.1
      prefix-length: 24
    dhcp: false
    enabled: true
  ipv6:
    autoconf: false
    dhcp: false
    enabled: false
  lldp:
    enabled: false
  mac-address: 52:54:00:9E:2A:87
  mtu: 1500

- name: virbr0-nic
  type: unknown
  state: down
  ipv4:
    enabled: false
  ipv6:
    enabled: false
  lldp:
    enabled: false
  mac-address: 52:54:00:9E:2A:87
  mtu: 1500
```

**Comment by ffmancera** [comment]
Hello! This bug should be fixed in nmstate-0.3.3. Could you update to nmstate-0.3.3? nmstate-0.3.3 is packaged on Fedora 32 so there shouldn't be any problem.

Please, let me know if you need anything else and close the ticket after verifying that it is fixed. If the bug persists, let me know and I'll work on it.

Thanks!

**Comment by hjensas** [comment]
Ok, upgraded to Fedora 33 and ``nmstate-0.3.3-1.fc33.noarch``, I also had some mistakes in my yaml defenition. But updating it to the defenition below seems to produce the bridge and interfaces I desire. 

```
interfaces:
  - name: br-leafs
    type: ovs-bridge
    state: up
    bridge:
      port:
        - name: pxeleaf0
          vlan:
            mode: access
            tag: 600
        - name: pxeleaf1
          vlan:
            mode: access
            tag: 601
        - name: pxeleaf2
          vlan:
            mode: access 
            tag: 602
        - name: pxeleaf3
          vlan:
            mode: access 
            tag: 603

  - name: pxeleaf0
    type: ovs-interface
    state: up
    ipv4:
      enabled: true
      address:
        - ip: 172.20.0.62
          prefix-length: 26
      dhcp: false
    ipv6:
      enabled: true
      address:
        - ip: fd12:3456:789a:0::fffe
          prefix-length: 64
      autoconf: false
      dhcp: false
  - name: pxeleaf1
    type: ovs-interface
    state: up
    ipv4:
      enabled: true
      address:
        - ip: 172.20.0.126
          prefix-length: 26
      dhcp: false
    ipv6:
      enabled: true
      address:
        - ip: fd12:3456:789a:1::fffe
          prefix-length: 64
      autoconf: false
      dhcp: false
  - name: pxeleaf2
    type: ovs-interface
    state: up
    ipv4:
      enabled: true
      address:
        - ip: 172.20.0.190
          prefix-length: 26
      dhcp: false
    ipv6:
      enabled: true
      address:
        - ip: fd12:3456:789a:2::fffe
          prefix-length: 64
      autoconf: false
      dhcp: false
  - name: pxeleaf3
    type: ovs-interface
    state: up
    ipv4:
      enabled: true
      address:
        - ip: 172.20.0.254
          prefix-length: 26
      dhcp: false
    ipv6:
      enabled: true
      address:
        - ip: fd12:3456:789a:3::fffe
          prefix-length: 64
      autoconf: false
      dhcp: false
```

**Comment by ffmancera** [comment]
Thanks!
