### ISSUE TITLE
catch-22 situation with RHEL/CentOS7 and infiniband

### ISSUE THREAD

**Issue by CJCShadowsan** [nmstate/nmstate#1421]
## Describe the bug
Whilst patches to enable Infiniband support works in later versions...

...The bump of NetworkManager to v1.22 causes issues in ipv6.dhcp-iaid property requests (as this doesn't exist in v1.18) and so fails to apply.

In a situation where users can't upgrade to rhel/centos 8, this leaves people stuck in a catch-22 situation if they have nodes with infiniband and NetworkManager v1.18 - as they end up either with errors with mac addresses that are too long, or requesting ipv6 iaid properties that don't exist.

## Nmstate version
- Version: 0.4.1

## NetworkManager version
- Version: 1.18

## Platform
- CentOS 7

## How reproducible
- 100%

## Steps to Reproduce

```
apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-bond0
spec:
  desiredState:
    interfaces:
    - name: br1
      description: Linux bridge with bond0 as a port
      type: linux-bridge
      state: up
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: bond0
```
## Nmstate output
- Expected output: Works

- Current output: 

If you use latest, you get hit with NetworkManager property issues:
```
[root@service01 conf]# kubectl get nnce service01.br1-bond0 -o jsonpath='{.status.conditions[?(@.type=="Failing")].message}'
error reconciling NodeNetworkConfigurationPolicy at desired state apply: , failed to execute nmstatectl set --no-commit --timeout 480: 'exit status 1' '' '2020-11-18 22:36:13,385 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/2 created for all devices: 480
2020-11-18 22:36:13,385 root         DEBUG    Adding new interfaces: ['br1']
2020-11-18 22:36:13,388 root         DEBUG    Editing interfaces: ['bond0']
2020-11-18 22:36:13,389 root         WARNING  IPv6 link local address fe80::b226:28ff:fefa:37b4/64 is ignored when applying desired state
2020-11-18 22:36:13,392 root         DEBUG    Executing NM action: func=add_connection_async
2020-11-18 22:36:13,394 root         ERROR    NM main-loop aborted: Connection adding failed: error=nm-connection-error-quark: ipv6.dhcp-iaid: unknown property (7)
```

If you downgrade, you get hit with lack of infiniband support:
```
    Message:               error reconciling NodeNetworkConfigurationPolicy at desired state apply: , failed to execute nmstatectl set --no-commit --timeout 480: 'exit status 1' '' 'Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==0.1.3', 'console_scripts', 'nmstatectl')()
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 59, in main
    return args.func(args)
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 221, in apply
    return apply_state(statedata, args.verify, args.commit, args.timeout)
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 237, in apply_state
    checkpoint = libnmstate.apply(state, verify_change, commit, timeout)
  File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 66, in apply
    state.State(desired_state), verify_change, commit, rollback_timeout
  File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 119, in _apply_ifaces_state
    current_state = state.State(netinfo.show())
  File "/usr/lib/python3.7/site-packages/libnmstate/netinfo.py", line 71, in show
    validator.validate(report)
  File "/usr/lib/python3.7/site-packages/libnmstate/validator.py", line 56, in validate
    js.validate(data, validation_schema)
  File "/usr/lib/python3.7/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: '20:00:10:87:FE:80:00:00:00:00:00:00:B8:59:9F:03:00:E6:66:B0' does not match '^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$'

Failed validating 'pattern' in schema['properties']['interfaces']['items']['allOf'][0]['properties']['mac-address']:
    {'pattern': '^([a-fA-F0-9]{2}:){5}[a-fA-F0-9]{2}$', 'type': 'string'}
```

**Comment by cathay4t** [comment]
@CJCShadowsan Nmstate has no plan to support RHEL/CentOS 7. The core code of Nmstate NetworkManger plugin is using `NM.Client.get_main_context()` which only exists on NM 1.22.

To get your use case done, you may try to use `rhel-system-roles` (`https://github.com/linux-system-roles/network/` ) instead.

Sorry for the late and not been helpful.
