### ISSUE TITLE
Unable to create trunk ports on OVS bridge

### ISSUE THREAD

**Issue by etcshad0vv** [nmstate/nmstate#1422]
## Describe the bug
I am not able to create trunk port on ovs bridge.

## Nmstate version
```bash
rpm -qi nmstate
Name        : nmstate
Version     : 0.2.10
Release     : 2.el8_2
```

## NetworkManager version
```bash
nmcli --version
nmcli tool, version 1.22.8-5.el8_2
```

## Platform
OpenShift v4.5.13

## How reproducible
- 100%

## Steps to Reproduce
You can try to use this definition:
```yaml
      interfaces:
      - name: dummy0
        type: dummy
        state: up
        ipv4:
          enabled: false
          dhcp: false
        ipv6:
          enabled: false
          dhcp: false            
      - name: ovs-bridge
        type: ovs-bridge
        state: up
        bridge:
          options:
            stp: false
          port:
            - name: dummy0
              vlan:
                mode: trunk
                trunk-tags:
                  - id: 10
                  - id-range:
                      min: 30
                      max: 50
```

## Nmstate output
```
2020-11-19 10:25:23,224 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/117 created for all devices: 60
2020-11-19 10:25:23,225 root         DEBUG    Adding new interfaces: ['ovs-bridge', 'dummy0']
2020-11-19 10:25:23,228 root         DEBUG    Editing interfaces: ['bond0', 'bond1']
2020-11-19 10:25:23,229 root         WARNING  IPv6 link local address fe80::ae1f:6bff:fec7:3538/64 is ignored when applying desired state
2020-11-19 10:25:23,232 root         DEBUG    Executing NM action: func=add_connection_async
2020-11-19 10:25:23,235 root         DEBUG    Connection adding succeeded: dev=dummy0
2020-11-19 10:25:23,235 root         DEBUG    Executing NM action: func=add_connection_async
2020-11-19 10:25:23,240 root         DEBUG    Connection adding succeeded: dev=ovs-bridge
2020-11-19 10:25:23,240 root         DEBUG    Executing NM action: func=add_connection_async
2020-11-19 10:25:23,243 root         DEBUG    Connection adding succeeded: dev=xHrfkPvacK39zjE
2020-11-19 10:25:23,243 root         DEBUG    Executing NM action: func=commit_changes_async
2020-11-19 10:25:23,248 root         DEBUG    Connection update succeeded: dev=bond0
2020-11-19 10:25:23,248 root         DEBUG    Executing NM action: func=commit_changes_async
2020-11-19 10:25:23,266 root         DEBUG    Connection update succeeded: dev=bond1
2020-11-19 10:25:23,266 root         DEBUG    Executing NM action: func=safe_activate_async
2020-11-19 10:25:23,273 root         DEBUG    Connection activation initiated: dev=ovs-bridge, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
2020-11-19 10:25:23,289 root         DEBUG    Connection activation succeeded: dev=ovs-bridge, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_IP_CONFIG of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_IS_MASTER | NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_MASTER_HAS_SLAVES of type NM.ActivationStateFlags>
2020-11-19 10:25:23,289 root         DEBUG    Executing NM action: func=safe_activate_async
2020-11-19 10:25:23,296 root         DEBUG    Connection activation initiated: dev=dummy0, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
2020-11-19 10:25:23,334 root         DEBUG    Connection activation succeeded: dev=dummy0, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATED of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_ACTIVATED of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_IS_SLAVE | NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_IP4_READY | NM_ACTIVATION_STATE_FLAG_IP6_READY of type NM.ActivationStateFlags>
2020-11-19 10:25:23,335 root         DEBUG    Executing NM action: func=_safe_modify_async
2020-11-19 10:25:23,337 root         DEBUG    Device reapply succeeded: dev=bond0
2020-11-19 10:25:23,337 root         DEBUG    Executing NM action: func=_safe_modify_async
2020-11-19 10:25:23,339 root         DEBUG    Device reapply succeeded: dev=bond1
2020-11-19 10:25:23,340 root         DEBUG    Executing NM action: func=safe_activate_async
2020-11-19 10:25:23,341 root         DEBUG    Connection activation initiated: dev=xHrfkPvacK39zjE, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
2020-11-19 10:25:23,351 root         DEBUG    Connection activation succeeded: dev=xHrfkPvacK39zjE, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATED of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_ACTIVATED of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_IS_MASTER | NM_ACTIVATION_STATE_FLAG_IS_SLAVE | NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_MASTER_HAS_SLAVES of type NM.ActivationStateFlags>
2020-11-19 10:25:23,351 root         DEBUG    NM action queue exhausted, quiting mainloop
2020-11-19 10:25:28,955 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/117 rollback executed: dbus.Dictionary({dbus.String('/org/freedesktop/NetworkManager/Devices/891'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3860'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3883'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2691'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2672'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3892'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3839'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/14'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2696'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3871'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/12'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/4450'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2834'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2684'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3872'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3863'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3838'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3875'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3889'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3849'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/4'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3850'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2694'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3864'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3342'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2679'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3877'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2267'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/4398'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3880'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/10'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3888'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3881'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2685'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/5'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3861'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3842'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3868'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2693'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3886'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3855'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3874'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2205'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/4449'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3879'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/1462'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3891'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/1'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/15'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3869'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3857'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2686'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3858'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3845'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2688'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3846'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/1463'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2682'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3878'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2675'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/4397'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2692'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2687'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2204'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/1834'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3844'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2681'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3851'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2677'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/21'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2697'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2695'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3865'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3853'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3862'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3873'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3876'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3854'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/16'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3890'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3867'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3866'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2678'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3837'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2683'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3340'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3841'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2208'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3341'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2673'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2858'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2837'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2670'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2698'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2690'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2689'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2674'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2680'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2839'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3847'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2671'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3856'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/13'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3840'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2836'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3870'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3343'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3882'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3859'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3852'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3885'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2699'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3887'): dbus.UInt32(0)}, signature=dbus.Signature('su'))
Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==0.2.10', 'console_scripts', 'nmstatectl')()
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 59, in main
    return args.func(args)
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 217, in apply
    statedata, args.verify, args.commit, args.timeout
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 241, in apply_state
    rollback_timeout=timeout,
  File "/usr/lib/python3.6/site-packages/libnmstate/deprecation.py", line 40, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/libnmstate/nm/nmclient.py", line 96, in wrapped
    ret = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 73, in apply
    state.State(desired_state), verify_change, commit, rollback_timeout
  File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 175, in _apply_ifaces_state
    _verify_change(desired_state)
  File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 221, in _verify_change
    verifiable_desired_state.verify_interfaces(current_state)
  File "/usr/lib/python3.6/site-packages/libnmstate/state.py", line 330, in verify_interfaces
    self._assert_interfaces_equal(other_state)
  File "/usr/lib/python3.6/site-packages/libnmstate/state.py", line 759, in _assert_interfaces_equal
    current_state.interfaces[ifname],
libnmstate.error.NmstateVerificationError:
desired
=======
---
name: ovs-bridge
type: ovs-bridge
state: up
bridge:
  options:
    fail-mode: ''
    mcast-snooping-enable: false
    rstp: false
    stp: false
  port:
  - name: dummy0
    vlan:
      mode: trunk
      trunk-tags:
      - id: 10
      - id-range:
          max: 50
          min: 30
ipv6:
  enabled: false

current
=======
---
name: ovs-bridge
type: ovs-bridge
state: up
bridge:
  options:
    fail-mode: ''
    mcast-snooping-enable: false
    rstp: false
    stp: false
  port:
  - name: dummy0
    vlan:
      mode: trunk
      tag: 0
ipv6:
  enabled: false

difference
==========
--- desired
+++ current
@@ -12,10 +12,6 @@
   - name: dummy0
     vlan:
       mode: trunk
-      trunk-tags:
-      - id: 10
-      - id-range:
-          max: 50
-          min: 30
+      tag: 0
 ipv6:
   enabled: false
```

**Comment by cathay4t** [comment]
@etcshad0vv The NetworkManager does not support the `trunk-tags` yet. Let me ask around see whether that's possible.

**Comment by joeltraber** [comment]
Whats the state of this?
