### ISSUE TITLE
Crash when using ovsdb plugin

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#1466]
## Describe the bug
When using ovsdb plugin the user is getting the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/vdsm/supervdsm_server.py", line 95, in wrapper
    res = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/vdsm/network/api.py", line 206, in setupNetworks
    _setup_networks(networks, bondings, options)
  File "/usr/lib/python3.6/site-packages/vdsm/network/api.py", line 230, in _setup_networks
    netswitch.configurator.setup(networks, bondings, options, in_rollback)
  File "/usr/lib/python3.6/site-packages/vdsm/network/netswitch/configurator.py", line 71, in setup
    _setup_nmstate(networks, bondings, options, in_rollback)
  File "/usr/lib/python3.6/site-packages/vdsm/network/netswitch/configurator.py", line 94, in _setup_nmstate
    nmstate.setup(desired_state, verify_change=not in_rollback)
  File "/usr/lib/python3.6/site-packages/vdsm/network/nmstate/api.py", line 49, in setup
    state_apply(desired_state, verify_change=verify_change)
  File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 71, in apply
    _apply_ifaces_state(plugins, net_state, verify_change, save_to_disk)
  File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 104, in _apply_ifaces_state
    plugin.apply_changes(net_state, save_to_disk)
  File "/usr/lib/python3.6/site-packages/libnmstate/plugins/nmstate_plugin_ovsdb.py", line 196, in apply_changes
    for iface in net_state.ifaces.all_ifaces():
AttributeError: 'Ifaces' object has no attribute 'all_ifaces'
```
##  Version
- nmstate-plugin-ovsdb-1.0.0-1.el8.noarch
- nmstate-1.0.0-1.el8.noarch
- nispor-1.0.1-2.el8.x86_64
- NetworkManager-1.30.0-0.4.el8.x86_64

## Platform
- Platform: el8

## How reproducible
- 100%

## Nmstate output
- Expected output:
- Do not crash because the function does not exist.

- Current output:
-  Crashing because the function does not exist.

**Comment by ffmancera** [comment]
I can confirm this is 100% reproducible. Tag v1.0.0 ovsdb plugin is broken because is using a function that does exist on 1.0.0 net_state.py. I am not sure why but it seems our linter didn't detect this and an integration test is missing.

**Comment by ffmancera** [comment]
This was caused due to a sync. issue when updating nmstate. The plugin was updated but the nmstate core was not. I am closing this and will reopen if it happens again.
