### ISSUE TITLE
Got failure when run `nmstate` in Fedora 29

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#161]
```
[root@f29 SPECS]# nmstatectl edit
Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 50, in main
    return args.func(args)
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 110, in edit
    new_state = _get_edited_state(txtstate, suffix, args.yaml)
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 172, in _get_edited_state
    txtstate = _run_editor(txtstate, suffix)
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 190, in _run_editor
    statefile.write(txtstate)
  File "/usr/lib64/python3.7/tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by cathay4t** [comment]
@tyll Can you take a look on this issue?

**Comment by cathay4t** [comment]
And also got error when running `nmstatectl` without any argument:

```
[root@f29 SPECS]# nmstatectl
Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 50, in main
    return args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```
