### ISSUE TITLE
Failed to attach `dummy_1` to bridge "interface name is longer than 15 chars"

### ISSUE THREAD

**Issue by phoracek** [nmstate/nmstate#189]
I manually created a `dummy_1` on node, then I tried to attach it to OVS bridge using following config:

```yaml
interfaces:
- name: ovs-br0
  type: ovs-bridge
  state: up
  bridge:
    options:
      fail-mode: ''
      mcast-snooping-enable: false
      rstp: false
      stp: true
    port:
    - name: dummy_1
      type: system
  ipv4:
    enabled: true
```

It failed with following:

```
2018-12-06 22:02:12,900 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/24 created for all devices: 60
2018-12-06 22:02:12,935 root         DEBUG    Connection settings for duplicate_settings:
id: d1
iface: d1
uuid: cc1d9d1a-bda1-4ed6-a56b-6dfb83d231a2
type: dummy
autoconnect: False
autoconnect_slaves: <enum NM_SETTING_CONNECTION_AUTOCONNECT_SLAVES_NO of type NM.SettingConnectionAutoconnectSlaves>
2018-12-06 22:02:12,938 root         DEBUG    Connection settings for duplicate_settings:
id: ovs-br0
iface: ovs-br0
uuid: 2317931f-b14e-46fe-b5cb-92048ae75b86
type: ovs-bridge
autoconnect: False
autoconnect_slaves: <enum NM_SETTING_CONNECTION_AUTOCONNECT_SLAVES_NO of type NM.SettingConnectionAutoconnectSlaves>
2018-12-06 22:02:12,940 root         DEBUG    Connection settings for create_setting:
id: dummy_1
iface: dummy_1
uuid: 6ca51dc0-e17d-4d90-9e9c-c76930caf420
type: dummy
autoconnect: False
autoconnect_slaves: <enum NM_SETTING_CONNECTION_AUTOCONNECT_SLAVES_NO of type NM.SettingConnectionAutoconnectSlaves>
2018-12-06 22:02:12,940 root         DEBUG    Connection settings for create_setting:
id: ovs-port-dummy_1
iface: ovs-port-dummy_1
uuid: b510f71c-f3b3-4d29-9659-1b1acde1c073
type: ovs-port
autoconnect: False
autoconnect_slaves: <enum NM_SETTING_CONNECTION_AUTOCONNECT_SLAVES_NO of type NM.SettingConnectionAutoconnectSlaves>
2018-12-06 22:02:12,942 root         DEBUG    Executing NM action: func=commit_changes_async, args=(True, <Gio.Cancellable object at 0x7f78851aae10 (GCancellable at 0x7f7874064250)>, <function _commit_changes_callback at 0x7f7886df8ed8>, (<libnmstate.nm.nmclient._MainLoop object at 0x7f7884c961d0>, <NM.DeviceDummy object at 0x7f78851aa960 (NMDeviceDummy at 0xf854f0)>))
2018-12-06 22:02:12,947 root         DEBUG    Connection update succeeded: dev=d1
2018-12-06 22:02:12,947 root         DEBUG    Executing NM action: func=commit_changes_async, args=(True, <Gio.Cancellable object at 0x7f78851aae10 (GCancellable at 0x7f7874064250)>, <function _commit_changes_callback at 0x7f7886df8ed8>, (<libnmstate.nm.nmclient._MainLoop object at 0x7f7884c961d0>, <NM.DeviceOvsBridge object at 0x7f78851aa8c0 (NMDeviceOvsBridge at 0xf87430)>))
2018-12-06 22:02:12,954 root         DEBUG    Connection update succeeded: dev=ovs-br0
2018-12-06 22:02:12,954 root         DEBUG    Executing NM action: func=add_connection_async, args=(<NM.SimpleConnection object at 0x7f78851aa1e0 (NMSimpleConnection at 0xf48180)>, True, <Gio.Cancellable object at 0x7f78851aae10 (GCancellable at 0x7f7874064250)>, <function _add_connection_callback at 0x7f7886df8d70>, <libnmstate.nm.nmclient._MainLoop object at 0x7f7884c961d0>)
2018-12-06 22:02:12,962 root         DEBUG    Connection adding succeeded: dev=dummy_1
2018-12-06 22:02:12,963 root         DEBUG    Executing NM action: func=add_connection_async, args=(<NM.SimpleConnection object at 0x7f78851aafa0 (NMSimpleConnection at 0xf44ee0)>, True, <Gio.Cancellable object at 0x7f78851aae10 (GCancellable at 0x7f7874064250)>, <function _add_connection_callback at 0x7f7886df8d70>, <libnmstate.nm.nmclient._MainLoop object at 0x7f7884c961d0>)
2018-12-06 22:02:12,965 root         ERROR    NM main-loop aborted: Connection adding failed: error=nm-connection-error-quark: connection.interface-name: 'ovs-port-dummy_1': interface name is longer than 15 characters (7)
2018-12-06 22:02:12,975 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/24 rollback executed: dbus.Dictionary({dbus.String(u'/org/freedesktop/NetworkManager/Devices/14'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/1'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/3'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/2'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/12'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/13'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/10'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/11'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/4'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/17'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/6'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/7'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/8'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/9'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/18'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/19'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/5'): dbus.UInt32(0L)}, signature=dbus.Signature('su'))
Traceback (most recent call last):
  File "/bin/nmstatectl", line 9, in <module>
    load_entry_point('nmstate==0.0.2', 'console_scripts', 'nmstatectl')()
  File "/usr/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 54, in main
    return args.func(args)
  File "/usr/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 147, in apply
    netapplier.apply(state, verify_change=args.verify)
  File "/usr/lib/python2.7/site-packages/libnmstate/netapplier.py", line 47, in apply
    _apply_ifaces_state(desired_state[Constants.INTERFACES], verify_change)
  File "/usr/lib/python2.7/site-packages/libnmstate/netapplier.py", line 64, in _apply_ifaces_state
    _edit_interfaces(ifaces_desired_state, ifaces_current_state)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/site-packages/libnmstate/netapplier.py", line 97, in _setup_providers
    raise ApplyError(mainloop.error)
libnmstate.netapplier.ApplyError: run execution
```

**Comment by tyll** [comment]
This is tracked in https://nmstate.atlassian.net/browse/NMSTATE-283?atlOrigin=eyJpIjoiMjFmMTg5NzdhNzc1NGJlMWIzZjk0OTQ0ODgxMWQwYmYiLCJwIjoiaiJ9
