### ISSUE TITLE
Invalid configuration producing big stack trace

### ISSUE THREAD

**Issue by javipolo** [nmstate/nmstate#1998]
## Describe the bug
Whenever there is an invalid configuration supplied to nmstate, the output is quite a verbose stack trace, and the very error is described at the bottom of the stack trace
Ideally stack trace should only be visible if some kind of debugging is enabled

## Nmstate version
- Version 1.3.0

## How reproducible
- 100%

## Steps to Reproduce
```
interfaces:
- name: eth0
  type: ethernet
  state: up
  ipv4:
    enabled: true
    dhcp: true
dns-resolver:
  config:
    server:
      - 10.1.2.3
```

## Nmstate output
- Expected output:
```
$ nmstate gc nmstate.yaml
Error: Failed to find suitable interface for saving DNS name servers: 10.1.2.3, nmstate only support saving DNS to interface with static gateway or auto interface with auto-dns:false
```
- Current output:
```
$ nmstate gc nmstate.yaml
Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==1.3.0', 'console_scripts', 'nmstatectl')()
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 74, in main
    return args.func(args)
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 397, in run_gen_config
    libnmstate.generate_configurations(state), use_yaml=use_yaml
  File "/usr/lib/python3.6/site-packages/libnmstate/nmstate.py", line 419, in generate_configurations
    net_state = NetState(desire_state, gen_conf_mode=True)
  File "/usr/lib/python3.6/site-packages/libnmstate/net_state.py", line 72, in __init__
    self._ifaces.gen_dns_metadata(self._dns, self._route)
  File "/usr/lib/python3.6/site-packages/libnmstate/ifaces/ifaces.py", line 668, in gen_dns_metadata
    iface_metadata = dns_state.gen_metadata(self, route_state)
  File "/usr/lib/python3.6/site-packages/libnmstate/dns.py", line 131, in gen_metadata
    "auto-dns:false" % server
libnmstate.error.NmstateValueError: Failed to find suitable interface for saving DNS name servers: 10.1.2.3, nmstate only support saving DNS to interface with static gateway or auto interface with auto-dns:false
```
### Additional context
We're using nmstatectl in assisted-installer and ideally we'd like to use the full output of nmstatecli to be presented to the user, but the stack trace is creating a lot of confussion
If we filter out the stack trace ourselves, it might happen that for other cases we're removing important debugging information

**Comment by cathay4t** [comment]
With nmstate 2.1+ (rust rewrite, targeting for RHEL 9.1+), the output changed to:

```bash
[fge@c9s dns]$ sudo nmstatectl gc bug.yml
[2022-08-08T08:20:22Z INFO  nmstate::ifaces::inter_ifaces] Adding interface eth0 with type ethernet, up priority 0
[2022-08-08T08:20:22Z ERROR nmstate::dns] InvalidArgument: Failed to find suitable(IP enabled with DHCP off or auto-dns: false) interface for DNS server ["10.1.2.3"]
NmstateError: InvalidArgument: Failed to find suitable(IP enabled with DHCP off or auto-dns: false) interface for DNS server ["10.1.2.3"]
```

The 1.x branch is entering maintenance stage for RHEL 8.x.

@javipolo Do you still need fix in 1.x branch?

**Comment by javipolo** [comment]
Yes @cathay4t, we would need the fix for the 1.x version ... :sweat_smile: 

We're working to migrate to the rust rewrite, but we're still far from it

Thanks a lot

**Comment by eformat** [comment]
i came across this one recently in dns.py and Single Node OpenShift using a single NIC (eth0 / 10.40.150.10/24) and OpenShiftSDN with a bridge for VM's. 

i worked around it by supplying a valid config (and found this bug issue along the way). 
just in case someone finds this useful !

```
cat <<EOF | oc apply -f -
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-policy
spec:
  desiredState:
    interfaces:
    - name: br1
      type: linux-bridge
      state: up
      ipv4:
        address:
        - ip: 10.40.150.10
          prefix-length: 24
        dhcp: false
        enabled: true
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: eth0
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 10.40.150.254
        next-hop-interface: br1
EOF
```
