### ISSUE TITLE
exception when trying to assign IP address to VLAN

### ISSUE THREAD

**Issue by yellowpattern** [nmstate/nmstate#2341]
## Describe the bug
Trying to assign a static IP address to a VLAN interface on a worker node in OpenShift fails.

## Nmstate version
- 1.3.3

## NetworkManager version
- Version [e.g. 1.24.2]

## Platform
- OpenShift 4.12

## How reproducible
- 100%

## Steps to Reproduce
cat <<__EOF| oc apply -f
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ens192-101-nncp-worker1
spec:
  nodeSelector:
    kubernetes.io/hostname: worker1
  desiredState:
    interfaces:
    - name: ens192.101
      description: Configuring ens192.101 on worker1
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.1.2
          prefix-length: 24
        enabled: true
        dhcp: false
__EOF

## Nmstate output
- Expected output:

- Current output:
The output below from the "messageEncoded" section here:
```
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationEnactment
metadata:
  creationTimestamp: "2023-05-12T04:22:51Z"
  generation: 1
  labels:
    nmstate.io/node: worker1
    nmstate.io/policy: ens192-101-policy-worker1
  name: worker1.ens192-101-policy-worker1
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: worker1
    uid: e682696d-74b9-4c0f-87cb-8d430338ad52
  resourceVersion: "19748579"
  uid: 84dba6eb-c010-4ea8-a2cb-ff953a518f41
status:
  conditions:
  - lastHeartbeatTime: "2023-05-12T04:22:58Z"
    lastTransitionTime: "2023-05-12T04:22:58Z"
    reason: FailedToConfigure
    status: "False"
    type: Progressing
  - lastHeartbeatTime: "2023-05-12T04:22:58Z"
    lastTransitionTime: "2023-05-12T04:22:58Z"
    message: |
      error reconciling NodeNetworkConfigurationPolicy at desired state apply: ,
      failed to execute nmstatectl set --no-commit --timeout 480: 'exit status 1'
      AttributeError
        'VlanIface' object has no attribute 'sriov_total_vfs'
    messageEncoded: ...
    reason: FailedToConfigure
    status: "True"
    type: Failing
```
Decoded message is:
```
error reconciling NodeNetworkConfigurationPolicy at desired state apply: ,
 failed to execute nmstatectl set --no-commit --timeout 480: 'exit status 1' '' '/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py:337: UserWarning: Using 'set' is deprecated, use 'apply' instead.
  warnings.warn("Using 'set' is deprecated, use 'apply' instead.")
2023-05-12 04:17:06,490 root         DEBUG    Nmstate version: 1.3.3
2023-05-12 04:17:06,491 root         DEBUG    Applying desire state: {'interfaces': [{'description': 'Configuring ens192.101 on worker1', 'ipv4': {'address': [{'ip': '198.18.0.18', 'prefix-length': 28}], 'dhcp': False, 'enabled': True}, 'name': 'ens192.101', 'state': 'up', 'type': 'ethernet'}]}
2023-05-12 04:17:06,491 root         WARNING  Failed to load plugin nmstate_plugin_ovsdb: No module named 'ovs'
2023-05-12 04:17:06,747 root         DEBUG    NetworkManager version 1.36.0
2023-05-12 04:17:06,796 root         DEBUG    Async action: Retrieve applied config: ethernet ens192 started
2023-05-12 04:17:06,797 root         DEBUG    Async action: Retrieve applied config: bridge br1 started
2023-05-12 04:17:06,797 root         DEBUG    Async action: Retrieve applied config: vlan ens192.100 started
2023-05-12 04:17:06,797 root         DEBUG    Async action: Retrieve applied config: bridge br101 started
2023-05-12 04:17:06,797 root         DEBUG    Async action: Retrieve applied config: vlan ens192.101 started
2023-05-12 04:17:06,797 root         DEBUG    Async action: Retrieve applied config: bridge br100 started
2023-05-12 04:17:06,798 root         DEBUG    Async action: Retrieve applied config: ethernet ens192 finished
2023-05-12 04:17:06,799 root         DEBUG    Async action: Retrieve applied config: bridge br1 finished
2023-05-12 04:17:06,800 root         DEBUG    Async action: Retrieve applied config: vlan ens192.100 finished
2023-05-12 04:17:06,800 root         DEBUG    Async action: Retrieve applied config: bridge br101 finished
2023-05-12 04:17:06,800 root         DEBUG    Async action: Retrieve applied config: vlan ens192.101 finished
2023-05-12 04:17:06,800 root         DEBUG    Async action: Retrieve applied config: bridge br100 finished
2023-05-12 04:17:06,803 root         DEBUG    Interface linux-bridge.br1 found. Merging the interface information.
2023-05-12 04:17:06,803 root         DEBUG    Interface linux-bridge.br100 found. Merging the interface information.
2023-05-12 04:17:06,803 root         DEBUG    Interface linux-bridge.br101 found. Merging the interface information.
2023-05-12 04:17:06,803 root         DEBUG    Interface ethernet.ens192 found. Merging the interface information.
2023-05-12 04:17:06,803 root         DEBUG    Interface vlan.ens192.100 found. Merging the interface information.
2023-05-12 04:17:06,803 root         DEBUG    Interface vlan.ens192.101 found. Merging the interface information.
Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==1.3.3', 'console_scripts', 'nmstatectl')()
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 74, in main
    return args.func(args)
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 338, in set
    return apply(args)
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 366, in apply
    args.save_to_disk,
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 419, in apply_state
    save_to_disk=save_to_disk,
  File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 86, in apply
    desired_state, ignored_ifnames, current_state, save_to_disk
  File "/usr/lib/python3.6/site-packages/libnmstate/net_state.py", line 51, in __init__
    gen_conf_mode,
  File "/usr/lib/python3.6/site-packages/libnmstate/ifaces/ifaces.py", line 154, in __init__
    self._mark_vf_interface_as_absent_when_sriov_vf_decrease()
  File "/usr/lib/python3.6/site-packages/libnmstate/ifaces/ifaces.py", line 256, in _mark_vf_interface_as_absent_when_sriov_vf_decrease
    cur_iface.sriov_total_vfs != 0
AttributeError: 'VlanIface' object has no attribute 'sriov_total_vfs'
```

**Comment by cathay4t** [comment]
@yellowpattern This is known issue and has been fixed in nmstate 1.4 branch. The 1.3 branch is unmaintained, please upgrade to 1.4 branch and try again.
