### ISSUE TITLE
Python issue

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [nmstate/nmstate#2564]
I dont know what the cause of this is,  and i dont know any additional troubleshooting steps i should take, i dont know if its a python versioning issue but i think its likely
```
spiderunderurbed@raspberrypi:~/nmstate.old $ nmstatectl
Traceback (most recent call last):
  File "/home/spiderunderurbed/.local/bin/nmstatectl", line 5, in <module>
    from nmstatectl.nmstatectl import main
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/nmstatectl/nmstatectl.py", line 31, in <module>
    import libnmstate
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/libnmstate/__init__.py", line 25, in <module>
    from .netapplier import apply
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/libnmstate/netapplier.py", line 27, in <module>
    from .nmstate import create_checkpoints
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/libnmstate/nmstate.py", line 31, in <module>
    from libnmstate.nm import NetworkManagerPlugin
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/libnmstate/nm/__init__.py", line 20, in <module>
    from . import applier
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/libnmstate/nm/applier.py", line 36, in <module>
    from . import bond
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/libnmstate/nm/bond.py", line 35, in <module>
    NM_SUPPORTED_BOND_OPTIONS = NM.SettingBond.get_valid_options(
                                ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'SettingBond'
```

**Comment by cathay4t** [comment]
It means you do not have gobject or NetworkManager-libnm installed.

Please try to install `python3-gobject-base` and `NetworkManager-libnm`.

Meanwhile, this 1.x branch is in maintenance mode(only security fix), please consider to use latest 2.x release where we rewrite nmstate into rust saving you from worry about dependency. If you don't want to compile it, try download the pre-compiled binary from https://github.com/nmstate/nmstate/releases

**Comment by SpiderUnderUrBed** [comment]
I believe I am using the latest version on nmstate. After installing the packages libnm-dev and python3-gi with apt, the initial issue got resolved, however, I cannot install `nispor` which nmstate needs to run, I tried installing it on python and apt, it was removed from PyPi awhile ago and I cant find any version of it on apt, do you know how to install it?
`spiderunderurbed@raspberrypi:~ $ nmstatectl
Traceback (most recent call last):
  File "/home/spiderunderurbed/.local/bin/nmstatectl", line 5, in <module>
    from nmstatectl.nmstatectl import main
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/nmstatectl/nmstatectl.py", line 31, in <module>
    import libnmstate
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/libnmstate/__init__.py", line 25, in <module>
    from .netapplier import apply
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/libnmstate/netapplier.py", line 27, in <module>
    from .nmstate import create_checkpoints
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/libnmstate/nmstate.py", line 37, in <module>
    from .nispor.plugin import NisporPlugin
  File "/home/spiderunderurbed/.local/lib/python3.11/site-packages/libnmstate/nispor/plugin.py", line 20, in <module>
    import nispor
ModuleNotFoundError: No module named 'nispor'`

**Comment by cathay4t** [comment]
If you want to build/install from tarball instead of using rpm/deb, please try:

```bash
PREFIX=/usr make install
```

**Comment by cathay4t** [comment]
latest(2.1+) nmstate does not depend on python-nispor anymore.
