### ISSUE TITLE
I cannot set ip address of a nic.

### ISSUE THREAD

**Issue by HlinaCZ** [nmstate/nmstate#493]
I am having issue running `nmstatectl set` with yaml file.
Any suggestions?

```
[root@node01 /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:55:00:d1:55:01 brd ff:ff:ff:ff:ff:ff
    inet 192.168.66.101/24 brd 192.168.66.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5055:ff:fed1:5501/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::369f:c5a1:f218:ebb9/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:12:34:57 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::cbfd:e021:78f5:36b8/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:9b:81:df:37 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global noprefixroute docker0
       valid_lft forever preferred_lft forever
6: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 12:de:b1:1a:4e:35 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::10de:b1ff:fe1a:4e35/64 scope link 
       valid_lft forever preferred_lft forever
7: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 0a:58:0a:f4:00:01 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::858:aff:fef4:1/64 scope link 
       valid_lft forever preferred_lft forever
8: vethcaf58af1@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default 
    link/ether a6:0b:8b:43:7e:09 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::a40b:8bff:fe43:7e09/64 scope link 
       valid_lft forever preferred_lft forever
9: veth82ac63b7@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default 
    link/ether 9e:a4:ac:64:3f:8e brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::9ca4:acff:fe64:3f8e/64 scope link 
       valid_lft forever preferred_lft forever
10: veth271b00ac@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master cni0 state UP group default 
    link/ether 52:84:e3:bb:20:8b brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::5084:e3ff:febb:208b/64 scope link 
       valid_lft forever preferred_lft forever
```

set.yaml:
```yaml
interfaces:
- name: eth1
  type: ethernet
  state: up
  ipv4:
    address:
    - ip: 192.168.100.192
      prefix-length: 24
    enabled: true
  ipv6:
    address:
    - ip: 2001:db8::2:1
      prefix-length: 64
    enabled: true
```

```
[root@node01 /]# nmstatectl set set.yaml            
2019-08-28 15:08:10,155 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/7 created for all devices: 60
2019-08-28 15:08:10,155 root         DEBUG    Adding new interfaces: []
2019-08-28 15:08:10,156 root         DEBUG    Editing interfaces: ['eth1']
2019-08-28 15:08:10,157 root         DEBUG    Connection settings for ConnectionSetting.import_by_profile:
id: Wired connection 1
iface: None
uuid: 7fa175bb-425a-33ed-9fc6-e79603b9ba1d
type: 802-3-ethernet
autoconnect: True
autoconnect_slaves: <enum NM_SETTING_CONNECTION_AUTOCONNECT_SLAVES_DEFAULT of type NM.SettingConnectionAutoconnectSlaves>
2019-08-28 15:08:10,159 root         DEBUG    Executing NM action: func=commit_changes_async
2019-08-28 15:08:10,165 root         DEBUG    Connection update succeeded: dev=eth1
2019-08-28 15:08:10,166 root         DEBUG    Executing NM action: func=_safe_modify_async
2019-08-28 15:08:10,166 root         DEBUG    Connection activation in progress: dev=eth1, state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
2019-08-28 15:08:30,177 root         WARNING  NM main-loop timed out.
2019-08-28 15:08:30,209 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/7 rollback executed: dbus.Dictionary({dbus.String(u'/org/freedesktop/NetworkManager/Devices/10'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/1'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/2'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/3'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/4'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/5'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/6'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/7'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/8'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/9'): dbus.UInt32(0L)}, signature=dbus.Signature('su'))
Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 9, in <module>
    load_entry_point('nmstate==0.0.8', 'console_scripts', 'nmstatectl')()
  File "/usr/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 62, in main
    return args.func(args)
  File "/usr/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 220, in apply
    statedata, args.verify, args.commit, args.timeout
  File "/usr/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 240, in apply_state
    checkpoint = libnmstate.apply(state, verify_change, commit, timeout)
  File "/usr/lib/python2.7/site-packages/libnmstate/netapplier.py", line 62, in apply
    state.State(desired_state), verify_change, commit, rollback_timeout
  File "/usr/lib/python2.7/site-packages/libnmstate/netapplier.py", line 142, in _apply_ifaces_state
    con_profiles=ifaces_add_configs + ifaces_edit_configs,
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/site-packages/libnmstate/netapplier.py", line 198, in _setup_providers
    mainloop.error
libnmstate.error.NmstateLibnmError: Unexpected failure of libnm when running the mainloop: run timeout
```

**Comment by EdDev** [comment]
@HlinaCZ, what nmstate version are you using? If you can recreate it, please enable NetworkManager trace logging and adjust the journal to catch all logs:

https://github.com/nmstate/nmstate/blob/master/packaging/docker_sys_config.sh#L3
and 
https://github.com/nmstate/nmstate/blob/master/packaging/docker_sys_config.sh#L9

**Comment by EdDev** [comment]
Please also share `nmcli con show eth1`.

**Comment by HlinaCZ** [comment]
Output of `nmcli con show`:
```
nmcli con show Wired\ connection\ 1 | cat
connection.id:                          Wired connection 1
connection.uuid:                        7fa175bb-425a-33ed-9fc6-e79603b9ba1d
connection.stable-id:                   --
connection.type:                        802-3-ethernet
connection.interface-name:              --
connection.autoconnect:                 yes
connection.autoconnect-priority:        -999
connection.autoconnect-retries:         -1 (default)
connection.auth-retries:                -1
connection.timestamp:                   1567599529
connection.read-only:                   no
connection.permissions:                 --
connection.zone:                        --
connection.master:                      --
connection.slave-type:                  --
connection.autoconnect-slaves:          -1 (default)
connection.secondaries:                 --
connection.gateway-ping-timeout:        0
connection.metered:                     unknown
connection.lldp:                        default
connection.mdns:                        -1 (default)
802-3-ethernet.port:                    --
802-3-ethernet.speed:                   0
802-3-ethernet.duplex:                  --
802-3-ethernet.auto-negotiate:          no
802-3-ethernet.mac-address:             52:54:00:12:34:56
802-3-ethernet.cloned-mac-address:      --
802-3-ethernet.generate-mac-address-mask:--
802-3-ethernet.mac-address-blacklist:   --
802-3-ethernet.mtu:                     auto
802-3-ethernet.s390-subchannels:        --
802-3-ethernet.s390-nettype:            --
802-3-ethernet.s390-options:            --
802-3-ethernet.wake-on-lan:             default
802-3-ethernet.wake-on-lan-password:    --
ipv4.method:                            auto
ipv4.dns:                               --
ipv4.dns-search:                        --
ipv4.dns-options:                       ""
ipv4.dns-priority:                      0
ipv4.addresses:                         --
ipv4.gateway:                           --
ipv4.routes:                            --
ipv4.route-metric:                      -1
ipv4.route-table:                       0 (unspec)
ipv4.ignore-auto-routes:                no
ipv4.ignore-auto-dns:                   no
ipv4.dhcp-client-id:                    --
ipv4.dhcp-timeout:                      0 (default)
ipv4.dhcp-send-hostname:                yes
ipv4.dhcp-hostname:                     --
ipv4.dhcp-fqdn:                         --
ipv4.never-default:                     no
ipv4.may-fail:                          yes
ipv4.dad-timeout:                       -1 (default)
ipv6.method:                            auto
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       ""
ipv6.dns-priority:                      0
ipv6.addresses:                         --
ipv6.gateway:                           --
ipv6.routes:                            --
ipv6.route-metric:                      -1
ipv6.route-table:                       0 (unspec)
ipv6.ignore-auto-routes:                no
ipv6.ignore-auto-dns:                   no
ipv6.never-default:                     no
ipv6.may-fail:                          yes
ipv6.ip6-privacy:                       -1 (unknown)
ipv6.addr-gen-mode:                     stable-privacy
ipv6.dhcp-duid:                         --
ipv6.dhcp-send-hostname:                yes
ipv6.dhcp-hostname:                     --
ipv6.token:                             --
proxy.method:                           none
proxy.browser-only:                     no
proxy.pac-url:                          --
proxy.pac-script:                       --
GENERAL.NAME:                           Wired connection 1
GENERAL.UUID:                           7fa175bb-425a-33ed-9fc6-e79603b9ba1d
GENERAL.DEVICES:                        eth1
GENERAL.STATE:                          activating
GENERAL.DEFAULT:                        no
GENERAL.DEFAULT6:                       no
GENERAL.SPEC-OBJECT:                    --
GENERAL.VPN:                            no
GENERAL.DBUS-PATH:                      /org/freedesktop/NetworkManager/ActiveConnection/2
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/Settings/2
GENERAL.ZONE:                           --
GENERAL.MASTER-PATH:                    --
```

**Comment by HlinaCZ** [comment]
Output of `nmcli con show eth1`:
```
[root@node01 /]# nmcli con show Wired\ connection\ 1 | cat
connection.id:                          Wired connection 1
connection.uuid:                        7fa175bb-425a-33ed-9fc6-e79603b9ba1d
connection.stable-id:                   --
connection.type:                        802-3-ethernet
connection.interface-name:              --
connection.autoconnect:                 yes
connection.autoconnect-priority:        -999
connection.autoconnect-retries:         -1 (default)
connection.auth-retries:                -1
connection.timestamp:                   1567600729
connection.read-only:                   no
connection.permissions:                 --
connection.zone:                        --
connection.master:                      --
connection.slave-type:                  --
connection.autoconnect-slaves:          -1 (default)
connection.secondaries:                 --
connection.gateway-ping-timeout:        0
connection.metered:                     unknown
connection.lldp:                        default
connection.mdns:                        -1 (default)
802-3-ethernet.port:                    --
802-3-ethernet.speed:                   0
802-3-ethernet.duplex:                  --
802-3-ethernet.auto-negotiate:          no
802-3-ethernet.mac-address:             52:54:00:12:34:56
802-3-ethernet.cloned-mac-address:      --
802-3-ethernet.generate-mac-address-mask:--
802-3-ethernet.mac-address-blacklist:   --
802-3-ethernet.mtu:                     auto
802-3-ethernet.s390-subchannels:        --
802-3-ethernet.s390-nettype:            --
802-3-ethernet.s390-options:            --
802-3-ethernet.wake-on-lan:             default
802-3-ethernet.wake-on-lan-password:    --
ipv4.method:                            auto
ipv4.dns:                               --
ipv4.dns-search:                        --
ipv4.dns-options:                       ""
ipv4.dns-priority:                      0
ipv4.addresses:                         --
ipv4.gateway:                           --
ipv4.routes:                            --
ipv4.route-metric:                      -1
ipv4.route-table:                       0 (unspec)
ipv4.ignore-auto-routes:                no
ipv4.ignore-auto-dns:                   no
ipv4.dhcp-client-id:                    --
ipv4.dhcp-timeout:                      0 (default)
ipv4.dhcp-send-hostname:                yes
ipv4.dhcp-hostname:                     --
ipv4.dhcp-fqdn:                         --
ipv4.never-default:                     no
ipv4.may-fail:                          yes
ipv4.dad-timeout:                       -1 (default)
ipv6.method:                            auto
ipv6.dns:                               --
ipv6.dns-search:                        --
ipv6.dns-options:                       ""
ipv6.dns-priority:                      0
ipv6.addresses:                         --
ipv6.gateway:                           --
ipv6.routes:                            --
ipv6.route-metric:                      -1
ipv6.route-table:                       0 (unspec)
ipv6.ignore-auto-routes:                no
ipv6.ignore-auto-dns:                   no
ipv6.never-default:                     no
ipv6.may-fail:                          yes
ipv6.ip6-privacy:                       -1 (unknown)
ipv6.addr-gen-mode:                     stable-privacy
ipv6.dhcp-duid:                         --
ipv6.dhcp-send-hostname:                yes
ipv6.dhcp-hostname:                     --
ipv6.token:                             --
proxy.method:                           none
proxy.browser-only:                     no
proxy.pac-url:                          --
proxy.pac-script:                       --
GENERAL.NAME:                           Wired connection 1
GENERAL.UUID:                           7fa175bb-425a-33ed-9fc6-e79603b9ba1d
GENERAL.DEVICES:                        eth1
GENERAL.STATE:                          activated
GENERAL.DEFAULT:                        no
GENERAL.DEFAULT6:                       no
GENERAL.SPEC-OBJECT:                    --
GENERAL.VPN:                            no
GENERAL.DBUS-PATH:                      /org/freedesktop/NetworkManager/ActiveConnection/2
GENERAL.CON-PATH:                       /org/freedesktop/NetworkManager/Settings/2
GENERAL.ZONE:                           --
GENERAL.MASTER-PATH:                    --
IP4.GATEWAY:                            --
IP6.ADDRESS[1]:                         fe80::8d6f:c7d0:23c2:35e4/64
IP6.GATEWAY:                            --
IP6.ROUTE[1]:                           dst = fe80::/64, nh = ::, mt = 101
IP6.ROUTE[2]:                           dst = ff00::/8, nh = ::, mt = 256, table=255
```

**Comment by HlinaCZ** [comment]
I am using nmstate version 0.0.8

**Comment by HlinaCZ** [comment]
There are the logs: [https://paste.fedoraproject.org/paste/51Kx8lk0zSuPTcqZLPn8vQ](https://paste.fedoraproject.org/paste/51Kx8lk0zSuPTcqZLPn8vQ)

**Comment by EdDev** [comment]
Looks similar to issue #494 .
The interface has already a dynamic IP enabled and the desired state does not request it to be disabled. If you explicitly set dhcp/autoconf to false, it should work.

**Comment by HlinaCZ** [comment]
Oh yeah, sorry, it is the same issue. I forgot about this opened issue.
