### ISSUE TITLE
ethernet example fails on `address` and `ethernet` diff

### ISSUE THREAD

**Issue by HlinaCZ** [nmstate/nmstate#494]
I installed fedora 30 server and tried your example but it doesn't work. Am I doing something wrong or is it a bug in nmstate 0.0.8? Thanks.
```
root@localhost ~]# cat /etc/redhat-release 
Fedora release 30 (Thirty)
[root@localhost ~]# rpm -qi nmstate
Name        : nmstate
Version     : 0.0.8
Release     : 1.fc30
Architecture: noarch
Install Date: Fri 30 Aug 2019 04:40:12 PM CEST
Group       : Unspecified
Size        : 27617
License     : LGPLv2+
Signature   : RSA/SHA256, Fri 26 Jul 2019 07:50:21 PM CEST, Key ID ef3c111fcfc659b9
Source RPM  : nmstate-0.0.8-1.fc30.src.rpm
Build Date  : Fri 26 Jul 2019 02:42:56 PM CEST
Build Host  : buildhw-07.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/nmstate/nmstate
Bug URL     : https://bugz.fedoraproject.org/nmstate
Summary     : Declarative network manager API
Description :
NMState is a library with an accompanying command line tool that manages host
networking settings in a declarative manner and aimed to satisfy enterprise
needs to manage host networking through a northbound declarative API and multi
provider support on the southbound.
[root@localhost ~]# cat set.yaml 
interfaces:
- name: enp7s0
  type: ethernet
  state: up
  ipv4:
    address:
    - ip: 192.168.122.250
      prefix-length: 24
    enabled: true
  ipv6:
    address:
    - ip: 2001:db8::1:1
      prefix-length: 64
    enabled: true
[root@localhost ~]# nmstatectl set set.yaml             
2019-08-30 16:48:50,114 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/7 created for all devices: 60
2019-08-30 16:48:50,115 root         DEBUG    Adding new interfaces: []
2019-08-30 16:48:50,115 root         DEBUG    Editing interfaces: ['enp7s0']
2019-08-30 16:48:50,117 root         DEBUG    Connection settings for ConnectionSetting.import_by_profile:
id: Wired connection 1
iface: None
uuid: 1a7e1072-3203-3a22-9f50-33d36c2ab0db
type: 802-3-ethernet
autoconnect: True
autoconnect_slaves: <enum NM_SETTING_CONNECTION_AUTOCONNECT_SLAVES_DEFAULT of type NM.SettingConnectionAutoconnectSlaves>
2019-08-30 16:48:50,120 root         DEBUG    Executing NM action: func=commit_changes_async
2019-08-30 16:48:50,126 root         DEBUG    Connection update succeeded: dev=enp7s0
2019-08-30 16:48:50,126 root         DEBUG    Executing NM action: func=_safe_modify_async
2019-08-30 16:48:50,129 root         DEBUG    Device reapply failed on enp7s0: error=nm-device-error-quark: Can't reapply changes to '802-3-ethernet.cloned-mac-address' setting (3)
Fallback to device activation
2019-08-30 16:48:50,194 root         DEBUG    Connection activation initiated: dev=enp7s0, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
2019-08-30 16:48:50,269 root         DEBUG    Connection activation succeeded: dev=enp7s0, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATED of type NM.ActiveConnectionState>
2019-08-30 16:48:50,269 root         DEBUG    NM action queue exhausted, quiting mainloop
2019-08-30 16:48:50,355 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/7 rollback executed: dbus.Dictionary({dbus.String('/org/freedesktop/NetworkManager/Devices/1'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2'): dbus.UInt32(0)}, signature=dbus.Signature('su'))
Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==0.0.8', 'console_scripts', 'nmstatectl')()
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 62, in main
    return args.func(args)
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 220, in apply
    statedata, args.verify, args.commit, args.timeout
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 240, in apply_state
    checkpoint = libnmstate.apply(state, verify_change, commit, timeout)
  File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 62, in apply
    state.State(desired_state), verify_change, commit, rollback_timeout
  File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 146, in _apply_ifaces_state
    _verify_change(desired_state)
  File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 184, in _verify_change
    desired_state.verify_interfaces(current_state)
  File "/usr/lib/python3.7/site-packages/libnmstate/state.py", line 257, in verify_interfaces
    self._assert_interfaces_equal(other_state)
  File "/usr/lib/python3.7/site-packages/libnmstate/state.py", line 485, in _assert_interfaces_equal
    current_state.interfaces[ifname],
libnmstate.error.NmstateVerificationError: 
desired
=======
---
name: enp7s0
type: ethernet
state: up
ipv4:
  address:
  - ip: 192.168.122.250
    prefix-length: 24
  auto-dns: true
  auto-gateway: true
  auto-routes: true
  dhcp: true
  enabled: true
ipv6:
  address:
  - ip: 2001:db8::1:1
    prefix-length: 64
  auto-dns: true
  auto-gateway: true
  auto-routes: true
  autoconf: true
  dhcp: true
  enabled: true
mac-address: 52:54:00:47:2F:24
mtu: 1500

current
=======
---
name: enp7s0
type: ethernet
state: up
ethernet:
  auto-negotiation: true
  duplex: full
  speed: 1000
ipv4:
  address: []
  auto-dns: true
  auto-gateway: true
  auto-routes: true
  dhcp: true
  enabled: true
ipv6:
  address: []
  auto-dns: true
  auto-gateway: true
  auto-routes: true
  autoconf: true
  dhcp: true
  enabled: true
mac-address: 52:54:00:47:2F:24
mtu: 1500

difference
==========
--- desired
+++ current
@@ -2,19 +2,19 @@
 name: enp7s0
 type: ethernet
 state: up
+ethernet:
+  auto-negotiation: true
+  duplex: full
+  speed: 1000
 ipv4:
-  address:
-  - ip: 192.168.122.250
-    prefix-length: 24
+  address: []
   auto-dns: true
   auto-gateway: true
   auto-routes: true
   dhcp: true
   enabled: true
 ipv6:
-  address:
-  - ip: 2001:db8::1:1
-    prefix-length: 64
+  address: []
   auto-dns: true
   auto-gateway: true
   auto-routes: true
```

**Comment by EdDev** [comment]
Looks like the interface `enp7s0` is already managed by NM and is set with IP method `auto`. Therefore, dhcp=true and you have not specified to disable it. Nmstate tries to keep it and ignores the mentioned static address (dhcp+static is not supported).
Try setting `dhcp: false` on both IPv4 and IPv6 and `autoconf: false` for IPv6.

We should probably provide a better error/warning to this scenario.
But the logic seems right.

**Comment by HlinaCZ** [comment]
Thanks. Disabling dhcp solved the problem.
