### ISSUE TITLE
Cannot apply "down" state when interface is already down

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#56]
When I try to apply the down state to an interface the second time it fails:

```
nmstatectl set <<EOF
{
    "interfaces": [
        {
            "state": "down", 
            "type": "ethernet", 
            "name": "eth2", 
            "ipv4": {
                "enabled": true, 
                "addresses": [
                    {
                        "ip": "192.0.2.14", 
                        "prefix-length": 30
                    }
                ]
            }
        }
    ]
}
EOF
2018-08-03 12:16:59,537 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/5 created for all devices: 60
2018-08-03 12:16:59,545 root         DEBUG    NM action queue exhausted, quiting mainloop
2018-08-03 12:17:19,561 root         WARNING  NM main-loop timed out.
2018-08-03 12:17:19,567 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/5 rollback executed: dbus.Dictionary({dbus.String(u'/org/freedesktop/NetworkManager/Devices/1'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/2'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/3'): dbus.UInt32(0L), dbus.String(u'/org/freedesktop/NetworkManager/Devices/4'): dbus.UInt32(0L)}, signature=dbus.Signature('su'))
Traceback (most recent call last):
  File "/root/.local/bin/nmstatectl", line 10, in <module>
    sys.exit(main())
  File "/root/.local/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 44, in main
    return args.func(args)
  File "/root/.local/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 116, in apply
    netapplier.apply(state)
  File "/root/.local/lib/python2.7/site-packages/libnmstate/netapplier.py", line 38, in apply
    _apply_ifaces_state(desired_state['interfaces'])
  File "/root/.local/lib/python2.7/site-packages/libnmstate/netapplier.py", line 52, in _apply_ifaces_state
    _edit_interfaces(ifaces_desired_state, ifaces_current_state)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/root/.local/lib/python2.7/site-packages/libnmstate/netapplier.py", line 74, in _setup_providers
    raise ApplyError(mainloop.error)
libnmstate.netapplier.ApplyError: run timeout
```

**Comment by tyll** [comment]
FTR, this is still a problem

**Comment by EdDev** [comment]
Fixed: https://github.com/nmstate/nmstate/blob/master/tests/integration/iface_admin_state_test.py#L28

**Comment by tyll** [comment]
thank you, it's fixed
