### ISSUE TITLE
removing/downing a bond interface requires full specification

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#72]
When I try to set a bond interface to down, it seems to require the full specification even though it will remove the config afterwards:

```
nmstatectl set <<EOF
interfaces:
- name: web-bond
  state: down
EOF

Traceback (most recent call last):
  File "/root/.local/bin/nmstatectl", line 10, in <module>
    sys.exit(main())
  File "/root/.local/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 44, in main
    return args.func(args)
  File "/root/.local/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 120, in apply
    netapplier.apply(state, verify_change=args.verify)
  File "/root/.local/lib/python2.7/site-packages/libnmstate/netapplier.py", line 40, in apply
    validator.verify(desired_state)
  File "/root/.local/lib/python2.7/site-packages/libnmstate/validator.py", line 38, in verify
    js.validate(data, validation_schema)
  File "/root/.local/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/root/.local/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: {'state': 'down', 'name': 'web-bond'} is valid under each of {'$ref': '#/definitions/interface-ethernet/rw'}, {'$ref': '#/definitions/interface-bond/rw'}, {'$ref': '#/definitions/interface-ovs-bridge/all'}, {'$ref': '#/definitions/interface-ovs-interface/rw'}, {'$ref': '#/definitions/interface-dummy/rw'}, {'$ref': '#/definitions/interface-unknown/rw'}

Failed validating 'oneOf' in schema['properties']['interfaces']['items']['allOf'][3]:
    {'oneOf': [{'$ref': '#/definitions/interface-unknown/rw'},
               {'$ref': '#/definitions/interface-ethernet/rw'},
               {'$ref': '#/definitions/interface-bond/rw'},
               {'$ref': '#/definitions/interface-ovs-bridge/all'},
               {'$ref': '#/definitions/interface-ovs-interface/rw'},
               {'$ref': '#/definitions/interface-dummy/rw'}]}

On instance['interfaces'][0]:
    {'name': 'web-bond', 'state': 'down'}
```

IMHO specifying the interface name and state should  be enough here.

**Comment by tyll** [comment]
This might be a generic problem. IIRC it is also not possible to just change the IP addresses of interfaces without specifying their type and maybe other options as well.

**Comment by tyll** [comment]
Just changing the mtu fails for certain:
```
{
    "interfaces": [
        {
            "name": "eth2",
            "mtu": 1501,
            "state": "up"
        }
    ]
}

```

Error:
```
Traceback (most recent call last):
  File "/root/.local/bin/nmstatectl", line 10, in <module>
    sys.exit(main())
  File "/root/.local/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 69, in main
    return args.func(args)
  File "/root/.local/lib/python2.7/site-packages/nmstatectl/nmstatectl.py", line 211, in edit
    netapplier.apply(new_state, verify_change=args.verify)
  File "/root/.local/lib/python2.7/site-packages/libnmstate/netapplier.py", line 40, in apply
    validator.verify(desired_state)
  File "/root/.local/lib/python2.7/site-packages/libnmstate/validator.py", line 38, in verify
    js.validate(data, validation_schema)
  File "/root/.local/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/root/.local/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: OrderedDict([('name', u'eth2'), (u'mtu', 1501), (u'state', u'up')]) is valid under each of {'$ref': '#/definitions/interface-ethernet/rw'}, {'$ref': '#/definitions/interface-bond/rw'}, {'$ref': '#/definitions/interface-ovs-bridge/all'}, {'$ref': '#/definitions/interface-ovs-interface/rw'}, {'$ref': '#/definitions/interface-dummy/rw'}, {'$ref': '#/definitions/interface-unknown/rw'}

Failed validating 'oneOf' in schema['properties']['interfaces']['items']['allOf'][3]:
    {'oneOf': [{'$ref': '#/definitions/interface-unknown/rw'},
               {'$ref': '#/definitions/interface-ethernet/rw'},
               {'$ref': '#/definitions/interface-bond/rw'},
               {'$ref': '#/definitions/interface-ovs-bridge/all'},
               {'$ref': '#/definitions/interface-ovs-interface/rw'},
               {'$ref': '#/definitions/interface-dummy/rw'}]}

On instance['interfaces'][0]:
    OrderedDict([('name', u'eth2'), (u'mtu', 1501), (u'state', u'up')])

```
