### ISSUE TITLE
Ethernet devices end up in a broken (not recoverable) state after they are detached from bonding

### ISSUE THREAD

**Issue by phoracek** [nmstate/nmstate#752]
Hello,

There is a race in nmstate. Not sure what is the cause. I would appreciate any help.

Reproducer:

```
echo '
interfaces:
- name: bond0
  type: bond
  state: up
  ipv4:
    dhcp: true
    enabled: true
  link-aggregation:
    mode: balance-rr
    slaves:
    - eth1
    - eth2
' > bond0_up.yaml

echo '
interfaces:
- name: bond0
  state: absent
' > bond0_absent.yaml

echo '
interfaces:
- name: eth1
  type: ethernet
  state: up
  ipv4:
    dhcp: true
    enabled: true
- name: eth2
  type: ethernet
  state: up
  ipv4:
    dhcp: true
    enabled: true
' > eth1-eth2_up.yaml

echo '
interfaces:
- name: eth1
  type: ethernet
  state: absent
- name: eth2
  type: ethernet
  state: absent
' > eth1-eth2_absent.yaml

while \
      nmstatectl set --no-commit bond0_up.yaml && \
      nmstatectl commit && \
      nmstatectl set --no-commit bond0_absent.yaml && \
      nmstatectl commit && \
      nmstatectl set --no-commit eth1-eth2_up.yaml && \
      nmstatectl commit && \
      nmstatectl set --no-commit eth1-eth2_absent.yaml && \
      nmstatectl commit; \
    do
      true
done
```

After several loops, it failed with following:

```
2020-02-05 13:14:04,531 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/175 
created for all devices: 60                                                                            
2020-02-05 13:14:04,531 root         DEBUG    Adding new interfaces: []
2020-02-05 13:14:04,532 root         DEBUG    Editing interfaces: ['eth2', 'eth1']
2020-02-05 13:14:04,532 root         DEBUG    Connection settings for ConnectionSetting.create:
id: eth2
iface: eth2
uuid: 15c546ea-d460-4292-b0b0-142bb22b8be4
type: 802-3-ethernet
autoconnect: True
autoconnect_slaves: <enum NM_SETTING_CONNECTION_AUTOCONNECT_SLAVES_YES of type NM.SettingConnectionAutoc
onnectSlaves>                                                                                          
2020-02-05 13:14:04,533 root         DEBUG    Connection settings for ConnectionSetting.create:
id: eth1
iface: eth1
uuid: 1e267ace-d1ae-47b4-a929-c0387750fca8
type: 802-3-ethernet
autoconnect: True
autoconnect_slaves: <enum NM_SETTING_CONNECTION_AUTOCONNECT_SLAVES_YES of type NM.SettingConnectionAutoc
onnectSlaves>                                                                                          
2020-02-05 13:14:04,536 root         DEBUG    Executing NM action: func=add_connection_async
2020-02-05 13:14:04,543 root         DEBUG    Connection adding succeeded: dev=eth2
2020-02-05 13:14:04,543 root         DEBUG    Executing NM action: func=add_connection_async
2020-02-05 13:14:04,549 root         DEBUG    Connection adding succeeded: dev=eth1
2020-02-05 13:14:04,549 root         DEBUG    Executing NM action: func=_safe_modify_async
2020-02-05 13:14:04,552 root         DEBUG    Device reapply failed on eth2: error=nm-device-error-quark
: Device is not activated (4)                                                                          
Fallback to device activation
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libnmstate/nm/connection.py", line 172, in _active_connection_c
allback                                                                                                
    nm_act_con = src_object.activate_connection_finish(result)
gi.repository.GLib.Error: nm-manager-error-quark: The device 'eth2' has no connections available for act
ivation. (2)                                                                                           

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libnmstate/nm/connection.py", line 192, in _active_connection_c
allback                                                                                                
    elif self._is_ovs_plugin_missing(e):
  File "/usr/lib/python3.7/site-packages/libnmstate/nm/connection.py", line 246, in _is_ovs_plugin_missi
ng                                                                                                     
    self._con_profile.is_type(
AttributeError: 'NoneType' object has no attribute 'is_type'
2020-02-05 13:15:04,548 root         WARNING  NM main-loop timed out.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 148, in _apply_ifaces_state
    con_profiles=ifaces_add_configs + ifaces_edit_configs,
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 215, in _setup_providers
    mainloop.error
libnmstate.error.NmstateLibnmError: Unexpected failure of libnm when running the mainloop: run timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/libnmstate/nm/checkpoint.py", line 135, in rollback
    result = self._manager.interface.CheckpointRollback(self._dbuspath)
  File "/usr/lib64/python3.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.NetworkManager.InvalidArguments: checkpoint /org/freedesk
top/NetworkManager/Checkpoint/175 does not exist                                                       

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==0.2.1', 'console_scripts', 'nmstatectl')()
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 59, in main
    return args.func(args)
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 217, in apply
    statedata, args.verify, args.commit, args.timeout
  File "/usr/lib/python3.7/site-packages/nmstatectl/nmstatectl.py", line 237, in apply_state
    checkpoint = libnmstate.apply(state, verify_change, commit, timeout)
  File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 66, in apply
    state.State(desired_state), verify_change, commit, rollback_timeout
  File "/usr/lib/python3.7/site-packages/libnmstate/netapplier.py", line 153, in _apply_ifaces_state
    _verify_change(desired_state)
  File "/usr/lib/python3.7/site-packages/libnmstate/nm/checkpoint.py", line 103, in __exit__
    self.rollback()
  File "/usr/lib/python3.7/site-packages/libnmstate/nm/checkpoint.py", line 137, in rollback
    raise NMCheckPointError(str(e))
libnmstate.nm.checkpoint.NMCheckPointError: org.freedesktop.NetworkManager.InvalidArguments: checkpoint 
/org/freedesktop/NetworkManager/Checkpoint/175 does not exist                                          
```

After this happens, I'm unable to set the interface up again:

```
[root@node01 vagrant]# nmcli c
NAME         UUID                                  TYPE      DEVICE  
System eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  ethernet  eth0    
cni0         f24162e6-06dc-48b2-a291-000167d3b96b  bridge    cni0    
docker0      881fda6e-5b40-49fa-9c38-ca49c9db4f98  bridge    docker0 
[root@node01 vagrant]# nmcli d
DEVICE        TYPE      STATE         CONNECTION  
eth0          ethernet  connected     System eth0 
cni0          bridge    connected     cni0        
docker0       bridge    connected     docker0     
flannel.1     vxlan     disconnected  --          
eth1          ethernet  unavailable   --          
eth2          ethernet  unavailable   --          
veth7d7da5e1  ethernet  unmanaged     --          
vetha14d0684  ethernet  unmanaged     --          
vethffa4a2bb  ethernet  unmanaged     --          
lo            loopback  unmanaged     --          
[root@node01 vagrant]# nmcli c add type ethernet ifname eth1
Connection 'ethernet-eth1' (b6542930-fd5c-4f7c-ba0c-be8965ed2d26) successfully added.
[root@node01 vagrant]# nmcli c up ethernet-eth1
Error: Connection activation failed: No suitable device found for this connection (device cni0 not avail
able because profile is not compatible with device (mismatching interface name)).                      
```

**Comment by cathay4t** [comment]
I tested on RHEL 8.1 with NetworkManager-1.22.6-1.el8.x86_64 and nmstate-0.2.3-1.el8.noarch.

No failure in 100 times retry:

```bash
for x in `seq 0 100`; do
      sudo nmstatectl set --no-commit bond0_up.yaml && \
      sudo nmstatectl commit && \
      sudo nmstatectl set --no-commit bond0_absent.yaml && \
      sudo nmstatectl commit && \
      sudo nmstatectl set --no-commit eth1-eth2_up.yaml && \
      sudo nmstatectl commit && \
      sudo nmstatectl set --no-commit eth1-eth2_absent.yaml && \
      sudo nmstatectl commit || break;
      echo $x
done
echo $x
```

@phoracek Which OS are you using? And which NetworkManager and nmstate.

**Comment by phoracek** [comment]
Thanks Gris. Indeed, I was not able to reproduce it with NetworkManager 1.22.

Closing the Issue.
