### ISSUE TITLE
Verification error with Broadcom BCM57840 NetXtreme II 10 Gigabit hardware

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#853]
This issue is only happening with Broadcom BCM57840 NetXtreme II 10 Gigabit hardware. 'nmstatectl show' works but when editting we are getting a verification error because the ethernet subtree is not present.

Please see the logs below:

```
[16:16:48@hp-dl388g8-04 ~]0# # got failure when just do 'nmstatectl edit ens2f1', save and quit directly:
[16:17:46@hp-dl388g8-04 ~]0# nmstatectl edit ens2f1
Applying the following state:
---
dns-resolver:
  config:
    search: []
    server: []
  running:
    search:
    - rhts.eng.pek2.redhat.com
    server:
    - 10.73.2.107
    - 10.73.2.108
    - 10.66.127.10
route-rules:
  config: []
routes:
  config: []
  running: []
interfaces:
- name: ens2f1
  type: ethernet
  state: up
  ethernet:
    auto-negotiation: true
    duplex: full
    speed: 1000
    sr-iov:
      total-vfs: 1
      vfs:
      - id: 0
        mac-address: ee:2a:4e:8e:71:f5
        spoof-check: true
        trust: false
  ipv4:
    dhcp: false
    enabled: false
  ipv6:
    autoconf: false
    dhcp: false
    enabled: false
  mac-address: A0:36:9F:00:2A:FB
  mtu: 1500
2020-02-25 16:17:54,507 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/9 created for all devices: 60
2020-02-25 16:17:54,507 root         DEBUG    Adding new interfaces: []
2020-02-25 16:17:54,509 root         DEBUG    Editing interfaces: ['ens2f1']
2020-02-25 16:17:54,514 root         DEBUG    Executing NM action: func=commit_changes_async
2020-02-25 16:17:54,519 root         DEBUG    Connection update succeeded: dev=ens2f1
2020-02-25 16:17:54,519 root         DEBUG    Executing NM action: func=_safe_modify_async
2020-02-25 16:17:54,521 root         DEBUG    Device reapply failed on ens2f1: error=nm-device-error-quark: Can't reapply any changes to 'sriov' setting (3)
Fallback to device activation
2020-02-25 16:17:54,525 root         DEBUG    Connection activation initiated: dev=ens2f1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
2020-02-25 16:17:57,109 root         DEBUG    Connection activation succeeded: dev=ens2f1, con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATED of type NM.ActiveConnectionState>, dev-state=<enum NM_DEVICE_STATE_ACTIVATED of type NM.DeviceState>, state-flags=<flags NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_IP4_READY | NM_ACTIVATION_STATE_FLAG_IP6_READY of type NM.ActivationStateFlags>
2020-02-25 16:17:57,610 root         DEBUG    NM action queue exhausted, quiting mainloop
2020-02-25 16:17:57,611 root         DEBUG    context.iteration() does not delete the context_busy_watcher, waiting 50 milliseconds
2020-02-25 16:17:57,668 root         DEBUG    Checkpoint /org/freedesktop/NetworkManager/Checkpoint/9 rollback executed: dbus.Dictionary({dbus.String('/org/freedesktop/NetworkManager/Devices/42'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/2'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/15'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/8'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/17'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/6'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/4'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/3'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/22'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/19'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/12'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/16'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/1'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/18'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/11'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/21'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/20'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/9'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/13'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/5'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/7'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/14'): dbus.UInt32(0), dbus.String('/org/freedesktop/NetworkManager/Devices/10'): dbus.UInt32(0)}, signature=dbus.Signature('su'))
Traceback (most recent call last):
  File "/usr/bin/nmstatectl", line 11, in <module>
    load_entry_point('nmstate==0.2.5', 'console_scripts', 'nmstatectl')()
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 59, in main
    return args.func(args)
  File "/usr/lib/python3.6/site-packages/nmstatectl/nmstatectl.py", line 191, in edit
    libnmstate.apply(new_state, verify_change=args.verify)
  File "/usr/lib/python3.6/site-packages/libnmstate/deprecation.py", line 40, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/libnmstate/nm/nmclient.py", line 98, in wrapped
    ret = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 70, in apply
    state.State(desired_state), verify_change, commit, rollback_timeout
  File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 158, in _apply_ifaces_state
    _verify_change(desired_state)
  File "/usr/lib/python3.6/site-packages/libnmstate/netapplier.py", line 202, in _verify_change
    desired_state.verify_interfaces(current_state)
  File "/usr/lib/python3.6/site-packages/libnmstate/state.py", line 329, in verify_interfaces
    self._assert_interfaces_equal(other_state)
  File "/usr/lib/python3.6/site-packages/libnmstate/state.py", line 703, in _assert_interfaces_equal
    current_state.interfaces[ifname],
libnmstate.error.NmstateVerificationError:
desired
=======
---
name: ens2f1
type: ethernet
state: up
ethernet:
  auto-negotiation: true
  duplex: full
  speed: 1000
  sr-iov:
    total-vfs: 1
    vfs:
    - id: 0
      mac-address: ee:2a:4e:8e:71:f5
      spoof-check: true
      trust: false
ipv4:
  enabled: false
ipv6:
  enabled: false
mac-address: A0:36:9F:00:2A:FB
mtu: 1500
 
current
=======
---
name: ens2f1
type: ethernet
state: up
ipv4:
  enabled: false
ipv6:
  enabled: false
mac-address: A0:36:9F:00:2A:FB
mtu: 1500
 
difference
==========
--- desired
+++ current
@@ -2,17 +2,6 @@
 name: ens2f1
 type: ethernet
 state: up
-ethernet:
-  auto-negotiation: true
-  duplex: full
-  speed: 1000
-  sr-iov:
-    total-vfs: 1
-    vfs:
-    - id: 0
-      mac-address: ee:2a:4e:8e:71:f5
-      spoof-check: true
-      trust: false
 ipv4:
   enabled: false
 ipv6:
   enabled: false
```

**Comment by ffmancera** [comment]
This is working well when using `nmstatectl edit ens2f1 --no-verify`.

**Comment by ffmancera** [comment]
Waiting for #865
